#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 19 12:44:54 2022

@author: jackchen
"""

# =============================================================================
'''

    Phonation feature
'''
# =============================================================================


New_Proximity_cols=[
 'Proximity[intensity_mean_mean(A:,i:,u:)]',
 'Proximity[meanF0_mean(A:,i:,u:)]',
 'Proximity[stdevF0_mean(A:,i:,u:)]',
 'Proximity[hnr_mean(A:,i:,u:)]',
 'Proximity[localJitter_mean(A:,i:,u:)]',
 'Proximity[localabsoluteJitter_mean(A:,i:,u:)]',
 # 'Proximity[rapJitter_mean(A:,i:,u:)]',
 # 'Proximity[ddpJitter_mean(A:,i:,u:)]',
 'Proximity[localShimmer_mean(A:,i:,u:)]',
 'Proximity[localdbShimmer_mean(A:,i:,u:)]',
 'Proximity[intensity_mean_var(A:,i:,u:)]',
 # 'Proximity[meanF0_var(A:,i:,u:)]',
 # 'Proximity[stdevF0_var(A:,i:,u:)]',
 # 'Proximity[hnr_var(A:,i:,u:)]',
 # 'Proximity[localJitter_var(A:,i:,u:)]',
 # 'Proximity[localabsoluteJitter_var(A:,i:,u:)]',
 # 'Proximity[rapJitter_var(A:,i:,u:)]',
 # 'Proximity[ddpJitter_var(A:,i:,u:)]',
 # 'Proximity[localShimmer_var(A:,i:,u:)]',
 # 'Proximity[localdbShimmer_var(A:,i:,u:)]',
 'Proximity[intensity_mean_max(A:,i:,u:)]',
 'Proximity[meanF0_max(A:,i:,u:)]',
 'Proximity[stdevF0_max(A:,i:,u:)]',
 'Proximity[hnr_max(A:,i:,u:)]',
 'Proximity[localJitter_max(A:,i:,u:)]',
 'Proximity[localabsoluteJitter_max(A:,i:,u:)]',
 # 'Proximity[rapJitter_max(A:,i:,u:)]',
 # 'Proximity[ddpJitter_max(A:,i:,u:)]',
 'Proximity[localShimmer_max(A:,i:,u:)]',
 'Proximity[localdbShimmer_max(A:,i:,u:)]'
 ]
New_Trend_D_cols=[
 'Trend[intensity_mean_mean(A:,i:,u:)]_d',
 'Trend[meanF0_mean(A:,i:,u:)]_d',
 'Trend[stdevF0_mean(A:,i:,u:)]_d',
 'Trend[hnr_mean(A:,i:,u:)]_d',
 'Trend[localJitter_mean(A:,i:,u:)]_d',
 'Trend[localabsoluteJitter_mean(A:,i:,u:)]_d',
 # 'Trend[rapJitter_mean(A:,i:,u:)]_d',
 # 'Trend[ddpJitter_mean(A:,i:,u:)]_d',
 'Trend[localShimmer_mean(A:,i:,u:)]_d',
 'Trend[localdbShimmer_mean(A:,i:,u:)]_d',
 # 'Trend[intensity_mean_var(A:,i:,u:)]_d',
 # 'Trend[meanF0_var(A:,i:,u:)]_d',
 # 'Trend[stdevF0_var(A:,i:,u:)]_d',
 # 'Trend[hnr_var(A:,i:,u:)]_d',
 # 'Trend[localJitter_var(A:,i:,u:)]_d',
 # 'Trend[localabsoluteJitter_var(A:,i:,u:)]_d',
 # 'Trend[rapJitter_var(A:,i:,u:)]_d',
 # 'Trend[ddpJitter_var(A:,i:,u:)]_d',
 # 'Trend[localShimmer_var(A:,i:,u:)]_d',
 # 'Trend[localdbShimmer_var(A:,i:,u:)]_d',
 'Trend[intensity_mean_max(A:,i:,u:)]_d',
 'Trend[meanF0_max(A:,i:,u:)]_d',
 'Trend[stdevF0_max(A:,i:,u:)]_d',
 'Trend[hnr_max(A:,i:,u:)]_d',
 'Trend[localJitter_max(A:,i:,u:)]_d',
 'Trend[localabsoluteJitter_max(A:,i:,u:)]_d',
 # 'Trend[rapJitter_max(A:,i:,u:)]_d',
 # 'Trend[ddpJitter_max(A:,i:,u:)]_d',
 'Trend[localShimmer_max(A:,i:,u:)]_d',
 'Trend[localdbShimmer_max(A:,i:,u:)]_d'
    ]
New_Trend_K_cols=[
 'Trend[intensity_mean_mean(A:,i:,u:)]_k',
 'Trend[meanF0_mean(A:,i:,u:)]_k',
 'Trend[stdevF0_mean(A:,i:,u:)]_k',
 'Trend[hnr_mean(A:,i:,u:)]_k',
 'Trend[localJitter_mean(A:,i:,u:)]_k',
 'Trend[localabsoluteJitter_mean(A:,i:,u:)]_k',
 # 'Trend[rapJitter_mean(A:,i:,u:)]_k',
 # 'Trend[ddpJitter_mean(A:,i:,u:)]_k',
 'Trend[localShimmer_mean(A:,i:,u:)]_k',
 'Trend[localdbShimmer_mean(A:,i:,u:)]_k',
 # 'Trend[intensity_mean_var(A:,i:,u:)]_k',
 # 'Trend[meanF0_var(A:,i:,u:)]_k',
 # 'Trend[stdevF0_var(A:,i:,u:)]_k',
 # 'Trend[hnr_var(A:,i:,u:)]_k',
 # 'Trend[localJitter_var(A:,i:,u:)]_k',
 # 'Trend[localabsoluteJitter_var(A:,i:,u:)]_k',
 # 'Trend[rapJitter_var(A:,i:,u:)]_k',
 # 'Trend[ddpJitter_var(A:,i:,u:)]_k',
 # 'Trend[localShimmer_var(A:,i:,u:)]_k',
 # 'Trend[localdbShimmer_var(A:,i:,u:)]_k',
 'Trend[intensity_mean_max(A:,i:,u:)]_k',
 'Trend[meanF0_max(A:,i:,u:)]_k',
 'Trend[stdevF0_max(A:,i:,u:)]_k',
 'Trend[hnr_max(A:,i:,u:)]_k',
 'Trend[localJitter_max(A:,i:,u:)]_k',
 'Trend[localabsoluteJitter_max(A:,i:,u:)]_k',
 # 'Trend[rapJitter_max(A:,i:,u:)]_k',
 # 'Trend[ddpJitter_max(A:,i:,u:)]_k',
 'Trend[localShimmer_max(A:,i:,u:)]_k',
 'Trend[localdbShimmer_max(A:,i:,u:)]_k'
    ]
New_Convergence_cols=[
 'Convergence[intensity_mean_mean(A:,i:,u:)]',
 'Convergence[meanF0_mean(A:,i:,u:)]',
 'Convergence[stdevF0_mean(A:,i:,u:)]',
 'Convergence[hnr_mean(A:,i:,u:)]',
 'Convergence[localJitter_mean(A:,i:,u:)]',
 'Convergence[localabsoluteJitter_mean(A:,i:,u:)]',
 # 'Convergence[rapJitter_mean(A:,i:,u:)]',
 # 'Convergence[ddpJitter_mean(A:,i:,u:)]',
 'Convergence[localShimmer_mean(A:,i:,u:)]',
 'Convergence[localdbShimmer_mean(A:,i:,u:)]',
 # 'Convergence[intensity_mean_var(A:,i:,u:)]',
 # 'Convergence[meanF0_var(A:,i:,u:)]',
 # 'Convergence[stdevF0_var(A:,i:,u:)]',
 # 'Convergence[hnr_var(A:,i:,u:)]',
 # 'Convergence[localJitter_var(A:,i:,u:)]',
 # 'Convergence[localabsoluteJitter_var(A:,i:,u:)]',
 # 'Convergence[rapJitter_var(A:,i:,u:)]',
 # 'Convergence[ddpJitter_var(A:,i:,u:)]',
 # 'Convergence[localShimmer_var(A:,i:,u:)]',
 # 'Convergence[localdbShimmer_var(A:,i:,u:)]',
 'Convergence[intensity_mean_max(A:,i:,u:)]',
 'Convergence[meanF0_max(A:,i:,u:)]',
 'Convergence[stdevF0_max(A:,i:,u:)]',
 'Convergence[hnr_max(A:,i:,u:)]',
 'Convergence[localJitter_max(A:,i:,u:)]',
 'Convergence[localabsoluteJitter_max(A:,i:,u:)]',
 # 'Convergence[rapJitter_max(A:,i:,u:)]',
 # 'Convergence[ddpJitter_max(A:,i:,u:)]',
 'Convergence[localShimmer_max(A:,i:,u:)]',
 'Convergence[localdbShimmer_max(A:,i:,u:)]'
 ]
New_Syncrony_cols=[
 'Syncrony[intensity_mean_mean(A:,i:,u:)]',
 'Syncrony[meanF0_mean(A:,i:,u:)]',
 'Syncrony[stdevF0_mean(A:,i:,u:)]',
 'Syncrony[hnr_mean(A:,i:,u:)]',
 'Syncrony[localJitter_mean(A:,i:,u:)]',
 'Syncrony[localabsoluteJitter_mean(A:,i:,u:)]',
 # 'Syncrony[rapJitter_mean(A:,i:,u:)]',
 # 'Syncrony[ddpJitter_mean(A:,i:,u:)]',
 'Syncrony[localShimmer_mean(A:,i:,u:)]',
 'Syncrony[localdbShimmer_mean(A:,i:,u:)]',
 # 'Syncrony[intensity_mean_var(A:,i:,u:)]',
 # 'Syncrony[meanF0_var(A:,i:,u:)]',
 # 'Syncrony[stdevF0_var(A:,i:,u:)]',
 # 'Syncrony[hnr_var(A:,i:,u:)]',
 # 'Syncrony[localJitter_var(A:,i:,u:)]',
 # 'Syncrony[localabsoluteJitter_var(A:,i:,u:)]',
 # 'Syncrony[rapJitter_var(A:,i:,u:)]',
 # 'Syncrony[ddpJitter_var(A:,i:,u:)]',
 # 'Syncrony[localShimmer_var(A:,i:,u:)]',
 # 'Syncrony[localdbShimmer_var(A:,i:,u:)]',
 'Syncrony[intensity_mean_max(A:,i:,u:)]',
 'Syncrony[meanF0_max(A:,i:,u:)]',
 'Syncrony[stdevF0_max(A:,i:,u:)]',
 'Syncrony[hnr_max(A:,i:,u:)]',
 'Syncrony[localJitter_max(A:,i:,u:)]',
 'Syncrony[localabsoluteJitter_max(A:,i:,u:)]',
 # 'Syncrony[rapJitter_max(A:,i:,u:)]',
 # 'Syncrony[ddpJitter_max(A:,i:,u:)]',
 'Syncrony[localShimmer_max(A:,i:,u:)]',
 'Syncrony[localdbShimmer_max(A:,i:,u:)]'
    
    ]